// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'firebase_options.dart'; // generated by FlutterFire CLI (optional)
import 'screens/register_screen.dart'; // adjust path if your files live elsewhere
import 'screens/main_screen.dart'; // adjust path if needed

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const ProviderScope(child: PowerPayApp()));
}

class PowerPayApp extends StatelessWidget {
  const PowerPayApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PowerPay',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.purple,
        scaffoldBackgroundColor: const Color(0xFFF7F0FA),
      ),
      home: const AuthWrapper(),
      // optional named routes:
      // routes: {
      //   '/home': (_) => const MainScreen(),
      //   '/register': (_) => const RegisterScreen(),
      // },
    );
  }
}

/// Shows a loader while initializing auth, then returns the correct screen:
/// - when logged in: MainScreen()
/// - when not logged in: RegisterScreen()
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // still waiting for the auth state
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // user is signed in
        if (snapshot.hasData && snapshot.data != null) {
          return const MainScreen();
        }

        // user is NOT signed in
        return const RegisterScreen();
      },
    );
  }
}
